/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_11 (number 1), GPIO_11 */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_11_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_11_SIGNAL                                 gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_GPIO_11_CHANNEL                                       11U   /*!< Signal channel */

/* GPIO_SD_05 (number 70), USER_BUTTON */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BUTTON_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BUTTON_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BUTTON_CHANNEL                                    5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BUTTON_GPIO                                    GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN                                   5U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN_MASK                      (1U << 5U)   /*!< GPIO pin mask */

/* GPIO_AD_14 (number 43), ADC12_6/J26[8] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC12_6_PERIPHERAL                                   ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC12_6_SIGNAL                                         IN   /*!< Signal name */
#define BOARD_INITPINS_ADC12_6_CHANNEL                                       14U   /*!< Signal channel */

/* GPIO_SD_02 (number 74), GPIO_SD_02/BT_CFG[0]/J57[2]/TP34 */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_02_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_02_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_GPIO_SD_02_CHANNEL                                     2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIO_SD_02_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIO_SD_02_GPIO_PIN                                    2U   /*!< GPIO pin number */
#define BOARD_INITPINS_GPIO_SD_02_GPIO_PIN_MASK                       (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_AD_02 (number 58), ADC12_2/J26[12]/J56[16] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC12_2_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_ADC12_2_SIGNAL                                 gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_ADC12_2_CHANNEL                                       16U   /*!< Signal channel */

/* GPIO_AD_03 (number 57), LPSPI1_SDI/J57[10]/U27[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SDI_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SDI_SIGNAL                              gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_LPSPI1_SDI_CHANNEL                                    17U   /*!< Signal channel */

/* GPIO_AD_01 (number 59), ADC12_1/J26[10]/J56[14] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC12_1_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_ADC12_1_SIGNAL                                 gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_ADC12_1_CHANNEL                                       15U   /*!< Signal channel */

/* GPIO_AD_04 (number 56), LPSPI1_SDO/J57[8]/U27[5] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SDO_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SDO_SIGNAL                              gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_LPSPI1_SDO_CHANNEL                                    18U   /*!< Signal channel */

/* GPIO_AD_05 (number 55), LPSPI1_PCS0/INT1_COMBO/J56[6]/J57[6]/U26[11]/U27[1] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_PCS0_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_PCS0_SIGNAL                             gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_LPSPI1_PCS0_CHANNEL                                   19U   /*!< Signal channel */

/* GPIO_AD_06 (number 52), LPSPI1_SCK/INT2_COMBO/J56[8]/J57[12]/U26[9]/U27[6] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SCK_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SCK_SIGNAL                              gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_LPSPI1_SCK_CHANNEL                                    20U   /*!< Signal channel */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_09 (number 3), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_SIGNAL                            RXD   /*!< Signal name */

/* GPIO_10 (number 2), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_SIGNAL                            TXD   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/* GPIO_SD_10 (number 65), FlexSPI_CLK */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_CLK_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_CLK_SIGNAL                     FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_09 (number 66), FlexSPI_D0_A */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D0_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D0_A_SIGNAL                   FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_07 (number 68), FlexSPI_D1_A */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D1_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D1_A_SIGNAL                   FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_08 (number 67), FlexSPI_D2_A */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D2_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D2_A_SIGNAL                   FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_11 (number 64), FlexSPI_D3_A */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D3_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D3_A_SIGNAL                   FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_SD_06 (number 69), FlexSPI_SS0 */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_SS0_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_SS0_SIGNAL                    FLEXSPI_A_SS0_B   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitQSPIPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
